# opencc_fmmseg.pyi

class OpenCC:
    def __init__(self, config: str = "s2t") -> None: ...
    def zho_check(self, input_text: str) -> int: ...
    def convert(self, input_text: str, punctuation: bool = False) -> str: ...